CREATE DATABASE MyMusic
GO
USE MyMusic

GO
-- Tạo bảng role
CREATE TABLE ROLE (
    id UNIQUEIDENTIFIER DEFAULT NEWID(),
    name NVARCHAR(40) NOT NULL,
    PRIMARY KEY (id)
)
-- Thêm dữ liệu vào bảng quyền
INSERT INTO ROLE (name) VALUES
    (N'Admin'),
    (N'Guest')
-- Tạo bảng người dùng
CREATE TABLE [USER] (
  id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  name NVARCHAR(40),
  email VARCHAR(40) NOT NULL,
  password VARCHAR(255) NOT NULL,
  birthday DATE,
  gender bit,
  image VARCHAR(MAX),
  phone VARCHAR(20),
  idRole UNIQUEIDENTIFIER,
  status bit NOT NULL,
  createAt DATETIME DEFAULT GETDATE() NOT NULL

);
-- Tạo bảng nghệ sĩ 
CREATE TABLE ARTIST (
  id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  name NVARCHAR(30) NOT NULL,
  country NVARCHAR(30),
  short_description NVARCHAR(MAX),
  image VARCHAR(255),
  status bit,
  createAt DATETIME DEFAULT GETDATE() NOT NULL

);
-- Tạo bảng thể loại
CREATE TABLE GENRE (
  id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  name NVARCHAR(255) NOT NULL,
  status bit,
  createAt DATETIME DEFAULT GETDATE() NOT NULL

);
-- Tạo bảng bài hát
CREATE TABLE SONG (
  id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY ,
  title NVARCHAR(255) NOT NULL,
  singer NVARCHAR(MAX),
  idGenre UNIQUEIDENTIFIER,
  lyrics NVARCHAR(MAX),
  image VARCHAR(255),
  path VARCHAR(255) NOT NULL,
  duration int,
  quantity int,
  status bit,
  createAt DATETIME DEFAULT GETDATE() NOT NULL
);
-- Danh sách phát
CREATE TABLE PLAYLIST (
  id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
  title NVARCHAR(255) NOT NULL,
  idUser UNIQUEIDENTIFIER,
  createAt DATETIME DEFAULT GETDATE() NOT NULL

);
-- Chi tiết danh sách 
CREATE TABLE PLAYLIST_DETAIL (
  id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	idPlaylist UNIQUEIDENTIFIER NOT NULL,
	idSong UNIQUEIDENTIFIER NOT NULL,
)
-- Đánh giá
CREATE TABLE SONG_RATED (
  id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	idSong UNIQUEIDENTIFIER NOT NULL,
	idUser UNIQUEIDENTIFIER NOT NULL,
	rate int DEFAULT 0,
  createAt DATETIME DEFAULT GETDATE() NOT NULL
)
-- Yêu thích
CREATE TABLE SONG_FAVOURITE(
  id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	idSong UNIQUEIDENTIFIER NOT NULL,
	idUser UNIQUEIDENTIFIER NOT NULL,
	status bit,
  createAt DATETIME DEFAULT GETDATE() NOT NULL
)
SELECT * FROM SONG

-- DROP DATABASE MyMusic